INSERT INTO USERS VALUES('user','user',TRUE);
INSERT INTO USERS VALUES('admin','admin',TRUE);

INSERT INTO AUTHORITIES VALUES('user','ROLE_USER');
INSERT INTO AUTHORITIES VALUES('admin','ROLE_ADMIN');