//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using System;
using NSubstitute;

namespace Cradle.Test
{
		[TestFixture]
		[Category ("CharaStatus Test")]
		public class CharaStatusTest
		{
			public IEffectController effect;
			public CharaStatusController status;

			[SetUp] public void Init()
			{ 
				effect = GetEffectMock ();
				status = GetControllerMock (effect);	
			}
		
			[TearDown] public void Cleanup()
			{

			}

			//正常値テスト
			[Test]
			[Category ("Calc Test")]
			public void CalcTimeTest ()
			{
				Assert.That (status.CalcTime(), Is.EqualTo (0.0f));
			}

			[Test]
			[Category ("Calc Test")]
			public void CalcHPTest () {
				status.CalcHP ();
				Assert.That (status.HP, Is.EqualTo(100));		
			}

			private IEffectController GetEffectMock () {
				return Substitute.For<IEffectController> ();
			}

			private CharaStatusController GetControllerMock(IEffectController effect) {
				var status = Substitute.For<CharaStatusController> ();
				status.SetEffectController (effect);
				status.CalcTime ().Returns (0.0f);
				return status;
			}

		}
}

