//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using System;

namespace Cradle.Test
{
		[TestFixture()]
		public class CharaStatusTest
		{
				[Test()]
				public void TestCase ()
				{
					
				}
		}
}

